# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8df9e7d62308cae8099825a043cd3c39"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "borosil-mrp-discount-vb"
handle = "borosil-mrp-discount-vb"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "arshiyas-development-store.myshopify.com"
